### ISSUE TITLE
Download oc command not working properly

### ISSUE THREAD

**Issue by gfvirga** [redhat-developer/openshift-vsts#117]
Giving the URL of the oc command is not working. It download fine, but the agent is expecting a path that does not exist. 
```
2019-11-08T14:38:13.8229035Z ##[section]Starting: oc-cmd 
2019-11-08T14:38:13.8233270Z ==============================================================================
2019-11-08T14:38:13.8233407Z Task         : Execute oc command
2019-11-08T14:38:13.8233484Z Description  : OpenShift execute CLI command.
2019-11-08T14:38:13.8233603Z Version      : 2.0.12
2019-11-08T14:38:13.8233673Z Author       : Hardy Ferentschik
2019-11-08T14:38:13.8233785Z Help         : See [getting started](https://github.com/redhat-developer/openshift-vsts/blob/master/docs/getting-started.md)
2019-11-08T14:38:13.8233859Z ==============================================================================
2019-11-08T14:38:15.5516244Z [command]/usr/bin/mkdir -p /home/gabe/vsts/_work/2/s/.download
2019-11-08T14:38:15.5694635Z [command]/usr/bin/curl -s -L -o /home/gabe/vsts/_work/2/s/.download/oc https://downloads-openshift-console.apps.osesbx.company.com/amd64/linux/oc
2019-11-08T14:38:17.1262610Z ##[error]ENOTDIR: not a directory, stat '/home/gabe/vsts/_work/2/s/.download/oc/oc'
2019-11-08T14:38:17.3421431Z ##[section]Finishing: oc-cmd 
```

## From Agent Server
```
[root@server .download]#     ls -l  /home/tdpogf0/vsts/_work/2/s/.download/
total 72628
-rw------- 1 gabe staff 74368728 Nov  8 09:38 oc

[root@server .download]# ls -l /home/gabe/vsts/_work/2/s/.download/oc/oc
ls: cannot access /home/gabe/vsts/_work/2/s/.download/oc/oc: No such file or directory
```

Manually moving the oc file to /home/gabe/vsts/_work/2/s/.download/oc/oc fixes the problem, but not ideal.

**Comment by lstocchi** [comment]
Hi @gfvirga, thanks for your feedback. It really helps us improving our extension. This is a problem already known and it should be fixed in the version we are going to release next week. I am sorry for the inconvenience.

Keep in mind we expect an archive as an input such as http://url.com/oc.tar.gz

**Comment by gfvirga** [comment]
I tried putting 4.2.2 in the version form and the pipeline hangs until it fails without any error.

This is output for the official file available at https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/

```
2019-11-08T16:46:12.4199219Z ##[section]Starting: oc-cmd 
2019-11-08T16:46:12.4203911Z ==============================================================================
2019-11-08T16:46:12.4204000Z Task         : Execute oc command
2019-11-08T16:46:12.4204096Z Description  : OpenShift execute CLI command.
2019-11-08T16:46:12.4204153Z Version      : 2.0.12
2019-11-08T16:46:12.4204246Z Author       : Hardy Ferentschik
2019-11-08T16:46:12.4204307Z Help         : See [getting started](https://github.com/redhat-developer/openshift-vsts/blob/master/docs/getting-started.md)
2019-11-08T16:46:12.4204416Z ==============================================================================
2019-11-08T16:46:14.1662725Z [command]/usr/bin/curl -s -L -o /home/gabe/vsts/_work/2/s/.download/openshift-client-linux-4.2.2.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.2.2.tar.gz
2019-11-08T16:46:21.9222810Z ##[error]ENOENT: no such file or directory, link 'oc' -> '/home/gabe/vsts/_work/2/s/.download/kubectl'
2019-11-08T16:46:22.1585665Z ##[section]Finishing: oc-cmd 
```

Also Openshift ships the command with .tar and not tar.gz
```
curl https://downloads-openshift-console.apps.osesbx.url.com/amd64/linux/ | grep oc
<li><a href="oc">oc@</a>
<li><a href="oc.tar">oc.tar</a>
<li><a href="oc.zip">oc.zip</a>
```

**Comment by lstocchi** [comment]
I suggest you to download oc from https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/ . btw i guess it won't work because you will end up with the same error you had before.The current released extension has clearly this bug.

.tar.gz was just an example, it supports .zip, .tar, .tgz ...

**Comment by lstocchi** [comment]
Hi @gfvirga, we just released the new version of the extension. This issue should now be fixed. Let us know if you have any other problem. Feel free to re-open it if you still face this issue. 
A suggestion if it doesn't work when updating the extension is to delete the _work folder bc it may have cached the older version :) Thank you

**Comment by deepaksinghnationwidecouk** [comment]
Hi,

This is still failing for us -

          - task: oc-setup@2
            displayName: oc login
            inputs:
              openshiftService: "Openshift-Dev-${{parameters.environmentName}}"
              version: 'https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz'

Azure Pipeline fails with -

Starting: oc login
==============================================================================
Task         : Install and setup oc
Description  : Installs oc and configures the PATH and KUBECONFIG environment variables.
Version      : 2.0.12
Author       : Hardy Ferentschik
Help         : See [getting started](https://github.com/redhat-developer/openshift-vsts/blob/master/docs/getting-started.md)
==============================================================================
/bin/mkdir -p /opt/ado-agent/ado-agent/_work/3/s/.download
/bin/curl -s -L -o /opt/ado-agent/ado-agent/_work/3/s/.download/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
##[error]ENOTDIR: not a directory, stat '/opt/ado-agent/ado-agent/_work/3/s/.download/oc/oc'
Finishing: oc login

Any (urgent) help would be much appreciated!

Regards,
Deepak

**Comment by lstocchi** [comment]
Hi @deepaksinghnationwidecouk, i tried with the release currently available in the marketplace and i'm not able to replicate it. Which version are you using? 1.5.0 right? Are you using a self-hosted or Microsoft-hosted agent?

**Comment by deepaksinghnationwidecouk** [comment]
Hi @lstocchi  - I've installed the latest extension currently available from the marketplace. We are using self-hosted agent. I've already tried with removing the _work folder and it still fails. Do you want me to run any diagnostics for you?

**Comment by lstocchi** [comment]
Could you please confirm that `/opt/ado-agent/ado-agent/_work/3/s/.download/oc` really exists?

**Comment by deepaksinghnationwidecouk** [comment]
Just ran the steps manually on the machine. The extracted oc is indeed a file although the extension expects a file?

[siaasadmin@devcd000002 ado-agent]$ pwd
/opt/ado-agent
[siaasadmin@devcd000002 ado-agent]$ mkdir -p /opt/ado-agent/ado-agent/_work/3/s/.download
[siaasadmin@devcd000002 ado-agent]$ curl -s -L -o /opt/ado-agent/ado-agent/_work/3/s/.download/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
[siaasadmin@devcd000002 ado-agent]$ cd /opt/ado-agent/ado-agent/_work/3/s/.download/
[siaasadmin@devcd000002 .download]$ tar xvfz oc.tar.gz
oc
[siaasadmin@devcd000002 .download]$ ls -lrt
total 107460
-rwxr-xr-x. 1 siaasadmin siaasadmin 84482424 Apr 18 05:58 oc
-rw-rw-r--. 1 siaasadmin siaasadmin 25553317 Apr 22 13:36 oc.tar.gz
[siaasadmin@devcd000002 .download]$ file oc
oc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=e00add0e21780eb8c644e5182465472722f3c561, stripped

**Comment by deepaksinghnationwidecouk** [comment]
> Could you please confirm that `/opt/ado-agent/ado-agent/_work/3/s/.download/oc` really exists?

The path doesn't exist once the pipeline/extensions throws an error. I think it's cleaning up after itself?

**Comment by lstocchi** [comment]
The download folder is deleted when the job starts so the oc should be there when the extension throws the error.

**Comment by deepaksinghnationwidecouk** [comment]
That's right - I can't find the directory path or oc after the pipeline exits with the error.

**Comment by lstocchi** [comment]
That's weird. Can you run the pipeline with the `Enable system diagnostics` checked and paste the log here?

**Comment by deepaksinghnationwidecouk** [comment]
Hi mate - sorry about the delay, was caught up in an internal outage. Here's the log for the oc-setup step in the pipeline:


##[debug]Evaluating condition for step: 'oc login'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: oc login
==============================================================================
Task         : Install and setup oc
Description  : Installs oc and configures the PATH and KUBECONFIG environment variables.
Version      : 2.0.12
Author       : Hardy Ferentschik
Help         : See [getting started](https://github.com/redhat-developer/openshift-vsts/blob/master/docs/getting-started.md)
==============================================================================
##[debug]agent.TempDirectory=/opt/ado-agent/ado-agent/_work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_OPENSHIFTSERVICE
##[debug]loading INPUT_VERSION
##[debug]loading ENDPOINT_AUTH_7cf47c46-e50c-4dda-a60f-7a4c545235ff
##[debug]loading ENDPOINT_AUTH_SCHEME_7cf47c46-e50c-4dda-a60f-7a4c545235ff
##[debug]loading ENDPOINT_AUTH_PARAMETER_7cf47c46-e50c-4dda-a60f-7a4c545235ff_KUBECONFIG
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_ACR_JSSPROXY1975_PASSWORD
##[debug]loading SECRET_ACR_JSSPROXY1975_USERNAME
##[debug]loading SECRET_BING_CUSTOM_SEARCH_SUBSCRIPTIONKEY
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loading SECRET_BING_CUSTOM_SEARCH_AUTOSUGGEST_SUBSCRIPTIONKEY
##[debug]loaded 13
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]version=https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
##[debug]creating download directory

**Comment by deepaksinghnationwidecouk** [comment]
Rest of the log -


##[debug]version=https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
##[debug]creating download directory
##[debug]downloading: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
##[debug]task result: Failed
##[error]ENOTDIR: not a directory, stat '/opt/ado-agent/ado-agent/_work/3/s/.download/oc/oc'
##[debug]Processed: ##vso[task.issue type=error;]ENOTDIR: not a directory, stat '/opt/ado-agent/ado-agent/_work/3/s/.download/oc/oc'
##[debug]Processed: ##vso[task.complete result=Failed;]ENOTDIR: not a directory, stat '/opt/ado-agent/ado-agent/_work/3/s/.download/oc/oc'
Finishing: oc login

**Comment by lstocchi** [comment]
@deepaksinghnationwidecouk if these are all the logs you see i think there is a problem with the code you have because they seems to be uncomplete. Can you copy the content of your` oc-setup-task.js` file located at `'/opt/ado-agent/ado-agent/_work/_tasks/oc-setup..../2.0.12/lib/`?

**Comment by deepaksinghnationwidecouk** [comment]
@lstocchi - I don't have this directory path on the filesystem, looks like the task is clearing after itself?

/opt/ado-agent/ado-agent

As a possible workaround, we already have the oc-cli baked into the self-hosted agent and don't really need to reinstall. However, we are interested in using the extension for "Openshift Service Connection". Is there a way we can skip the installation in favour of already available binary as part of oc-setup@2?

**Comment by lstocchi** [comment]
@deepaksinghnationwidecouk that's really weird. The task folder should be there.

Yes, to skip the installation and use the oc cli already installed in the machine you can check the `Use local oc executable` and don't write any version. The only thing you have to make sure is to have oc in your PATH

![image](https://user-images.githubusercontent.com/49404737/80077732-3157c380-854e-11ea-8434-54a223c9ba32.png)

```
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    cmd: 'version'
    uselocalOc: true
```

**Comment by deepaksinghnationwidecouk** [comment]
@lstocchi - Tried that but its unable to pick up local oc even though it exists in the PATH. Please see attached.
[oc-setup.txt](https://github.com/redhat-developer/openshift-vsts/files/4521407/oc-setup.txt)
[test-local-oc.txt](https://github.com/redhat-developer/openshift-vsts/files/4521408/test-local-oc.txt)

**Comment by lstocchi** [comment]
@deepaksinghnationwidecouk when using the local oc you need to use the other task `oc cmd` or `oc configmap`. The setup task doesn't support the local oc because there is no reason for that. If you use the `setup oc` task it will try to download oc requested and add it to the PATH but if you already have an oc-cli locally you can skip that task and use directly `oc-cmd`.

Can you please share your full pipeline? Can you please try to create a pipeline with a single step as the one i copied above and see what's the output?

**Comment by deepaksinghnationwidecouk** [comment]
Here's the complete pipeline:

stages:
  - stage: release_to_prReview
    displayName: Release to PR-Review Environment
    jobs:
      - deployment: deploy
        displayName: Deploy
        pool:
          name: NBS-MC-COUK-SC-NP-DEPLOY
        environment: "prReview"
        strategy:
          runOnce:
            deploy:
              steps:
              - script: |
                  echo $PATH
                  oc version
                displayName: Test local oc
              - task: oc-setup@2
                displayName: oc login
                inputs:
                  openshiftService: "Openshift-Dev-prReview"
                  version: '4.3.8'
                  uselocalOc: true

**Comment by deepaksinghnationwidecouk** [comment]
We're using "script" task to set some variables before invoking oc commands and then doing something with the output. So can;t use oc-cmd@2. oc-setup@2 seems to be the only way to enable the Openshift connection for subsequent script tasks.

**Comment by lstocchi** [comment]
You're trying to download a version which doesn't exist in the repo the extension currently uses. It will be fixed in new release which is going to be published in next days. What you can try now is to change the version to '4.3' or 4.4 or 4.5.

```
- task: oc-setup@2
displayName: oc login
inputs:
openshiftService: "Openshift-Dev-prReview"
version: '4.3'
```

My test:

```
steps:
- task: oc-setup@2
  inputs:
    openshiftService: 'CRC'
    version: '4.3'
- script: oc get pods
```

Output:
![image](https://user-images.githubusercontent.com/49404737/80084057-a8915580-8556-11ea-8c5a-80e9157f3ffc.png)

![image](https://user-images.githubusercontent.com/49404737/80084087-b47d1780-8556-11ea-89f6-972cdf0ed472.png)

**Comment by deepaksinghnationwidecouk** [comment]
Still fails for me with 4.3. We have decided to disable the extension for now and use kubeconfig for logging in. Can carry on troubleshooting with you afterwards.

##[debug]version=4.3
##[debug]creating download directory
##[debug]determining tarball URL for tag 4.3
##[debug]Error retrieving tagged release {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/releases/#get-a-release-by-tag-name"}
##[debug]archive URL: null
##[debug]task result: Failed
##[error]Unable to determine oc download URL.
##[debug]Processed: ##vso[task.issue type=error;]Unable to determine oc download URL.
##[debug]Processed: ##vso[task.complete result=Failed;]Unable to determine oc download URL.
##[debug]task result: Failed
##[error]no oc binary found
##[debug]Processed: ##vso[task.issue type=error;]no oc binary found
##[debug]Processed: ##vso[task.complete result=Failed;]no oc binary found
Finishing: oc login

**Comment by lstocchi** [comment]
Ok. Closing this issue as this is not related to this for me. Feel free to open a new issue whenever you want. Just a small note:
In my test i have such a log
```
##[debug]version=4.3
##[debug]proxy=undefined
##[debug]creating download directory
##[debug]testing directory '/home/luca/Public/azure/myagent/_work/1/s/.download'
##[debug]testing directory '/home/luca/Public/azure/myagent/_work/1/s'
##[debug]mkdir '/home/luca/Public/azure/myagent/_work/1/s/.download'
##[debug]determining tarball URL for version 4.3
```
As you can see it is quite different, not because of the directory path but because of the log messages i get, such as `proxy=undefined` and `determining tarball URL for version 4.3` which make me think your agent is using an older version.

For instance we changed the message from `determining tarball URL for tag` to `determining tarball URL for version` in November 2019 https://github.com/redhat-developer/openshift-vsts/commit/a80d05585d3597587638fddfeb180b8650407347#diff-ecfa23cf26b1fb19d7f1126927c80181R128 

I guess you have some issue with your agent and it's really difficult for me to help on it.

**Comment by deepaksinghnationwidecouk** [comment]
Thanks @lstocchi  - is it the extension version you would suggest upgrading or the vsts agent?

**Comment by lstocchi** [comment]
I would try by using a new vsts agent. I would also remove the extension from azure devops account and reinstall it. It may happen it has some issues with its cache.

**Comment by deepaksinghnationwidecouk** [comment]
Thanks - sounds like a plan! Will update once I've had a chance to test. Thanks for all your help - much appreciated!
