### ISSUE TITLE
Unable to locate executable file: 'mkdir'

### ISSUE THREAD

**Issue by Dauit** [redhat-developer/openshift-vsts#133]
Hi

I'm trying to get the extension to work for us.

We are behind heavy proxy, so I won't be able to download the latest version from Github but are forced to use the version of OC that we have installed(3.11.0) on the build agent(windows hosted) and in our Openshift environment. Our Openshift cluster is on-prem, same goes with Azure Devops Server which we are running with the latest LTS version. And the latest version of the extension, 1.4.2

I've set the oc path in system env also if that makes any different.

When I specify to use 3.11.0 i get this error; 
`Unable to locate executable file: 'mkdir'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.`

**Comment by lstocchi** [comment]
Hi @Dauit, this error is something i have already seen but it should be fixed. We are now using built-in azure pipeline function to create a new directory so it seems weird to me that error. 

The problem could be in your agent bc it doesn't update the code when we install a new version of the extension. Could you please do a quick check and verify the oc-install.js file you have locally is the newest one? 

To do that, go to your agent directory -> get inside folder _work -> get into _tasks -> here you should find an oc-cmd_****** folder -> 2.0.12 -> lib -> you should be in a path similar to `c://luca/azure/myagent/_work/_tasks/oc-cmd_ebaf1cdc-a60f-4e57-ba29-e3b8f80aeb1e/2.0.12/lib` and you should find a file called oc-install.js -> open it and check if you can find the word `mkdirP`. If you don't find it, it means your agent is using an old version of the extension. Just delete the _work folder. It will be recreated by the agent with the newer code. Could you please let me know?

**Comment by Dauit** [comment]
Hi @lstocchi Thank you for the fast response!

I can't find the word `mkdirP` but I can however find `mkdir`, perhaps a typeo from you?

Anyway, I deleted the `oc-cmd` folder and ran the build again. Got the same error, and mkdir(and not mkdirp) still exist in oc-install-js

And last thing I did was to delete the folder `oc-setup` and also the folder where the code is being placed on the server when building, still getting the same error and the folders `oc-cmd` and `oc-setup` is there again when after building :(

**Comment by lstocchi** [comment]
@Dauit no typo, there should really be a `mkdirP` :)
The old code was 
```
let mkdir: ToolRunner = tl.tool('mkdir');
mkdir.arg('-p').arg(downloadDir);
await mkdir.exec();
```
and it was replaced by 
```
 tl.mkdirP(downloadDir);
```
So if you see the code in the first block it's like your agent is stuck on a previous version. 
I tried again on my Windows machine and it works fine. You said you deleted the oc-cmd folder. Have you tried by deleting the folder `_work`? It will force the agent to download everything again. Other thing you can try is to remove the extension from your azure devops account and re-install it. 
These are the only ideas i have atm. It seems to me an azure cache problem and i usually fix it by doing these 2 steps

**Comment by lstocchi** [comment]
Hi @Dauit , have you been able to run the extension or you still face this error?

**Comment by Dauit** [comment]
Hi @lstocchi  sorry for the late replay, I had to focus on other issues. I will get back to you on Wednesday with an update!

**Comment by Dauit** [comment]
Hi

Sorry for the late response.

The issue I had was that I was building with a code with a ps1 file that set alot of things that messed things up for me.

Anyway, When we tried again we got this error: `request to https://mirror.openshift.com/pub/openshift-v3/clients/D:/SoftWare/oc-3.11.0/oc.exe/windows/oc.zip failed, reason: getaddrinfo ENOTFOUND mirror.openshift.com mirror.openshift.com:443` and also the `mkdir `error

So I have tried with:
3.11.0 (that we have installed)
D:\SoftWare\oc-3.11.0\oc.exe (where it's installed)

We have it installed on the server, in the path `D:\SoftWare\oc-3.11.0\oc.exe` but can't find it and we don't allow to go external to get the version of OC. How should I reference it so that oc-setup can find it on the server

Br
David

**Comment by lstocchi** [comment]
Hi @Dauit,
Yeah the error you have (`request to https://mirror.openshift.com/pub/openshift-v3/clients/D:/SoftWare/oc-3.11.0/oc.exe/windows/oc.zip failed, reason: getaddrinfo ENOTFOUND mirror.openshift.com mirror.openshift.com:443`) it's related to proxies. We are adding support for it but it has not been published yet.

Have you had the chance to delete the `_work` folder and see if its content got updated by the agent? Last time, you told me you didn't find any sign of `mkdirP` in the code and that one could be a problem.

Then, if you want to use the local oc, without downloading a new version, you need to add the flag `uselocalOc: true` to your pipeline. In this case you don't need to use the `oc-setup` task because oc is already setup by you (have you added oc to your $PATH? if not, add it or the extension won't know where to find it). Now, you can directly use the oc-cmd task and specify you want to use the local Oc. You should end up having something like 

```
steps:
- task: oc-cmd@2
  inputs:
    openshiftService: 'My Openshift'
    cmd: 'oc status'
    uselocalOc: true
```

**Comment by MagnusTim** [comment]
Hi, Magnus here, colleague of David,
We tried the `uselocalOc: true` and set a path to oc.exe on our build server and manually removed all oc task folders from `.. _work/_tasks..`, then it seem to work. Thanks.

**Comment by lstocchi** [comment]
@MagnusTim that's awesome :) Happy you were able to solve this. Thanks for letting me know. 
Closing it. Feel free to reopen it or open a new issue in case you will encounter other problems :)
